### ISSUE TITLE
Chapter 7 - archiver_v2 question

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#10]
The code for the modified main() method reads:

    def main():
        args = get_args()
        if args.output:
            output = pathlib.Path(args.output)
            input_paths = get_paths(args.input_path)
        else:
            temp = pathlib.Path(args.input_path)
            output = pathlib.Path(f'{temp}.tar')
        controller.create_tar(output, archive_objects=[input_paths])
        print(f'Created tarball from {input_path} to {output}')

However, input_path in the final print statement throws an error as being undefined because get_paths() returns a list, not a string.

**Comment by cmcknight** [comment]
Disregard, I missed removing the square brackets in the controller.create_tar line.

**Comment by driscollis** [comment]
Glad you figured this one out
