### ISSUE TITLE
Chapter 7 - update_archive() column defs in the repo different from book text

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#12]
The code in the book is:

        self.archive_olv.SetColumns([
            ColumnDefn("Name", "left", 350, "name"),
            ColumnDefn("Path", "left", 350, "path"),
            ColumnDefn("Size", "left", 75, "size"),
            ColumnDefn("Type", "right", 75, "type"),
            ColumnDefn("Modified", "left", 150, "modified")])

but the code in the repo is:

        self.archive_olv.SetColumns([
            ColumnDefn("Name", "left", 100, "name"),
            ColumnDefn("Path", "left", 350, "path"),
            ColumnDefn("Size", "left", 75, "size"),
            ColumnDefn("Type", "right", 75, "item_type"),
            ColumnDefn("Modified", "left", 150, "modified")])

**Comment by driscollis** [comment]
This has already been fixed. I think it went out in the Friday batch. Do you have the latest version of the book? Regardless, I will push out another update tonight

**Comment by cmcknight** [comment]
Cool, I re-pullled the repo code and redownloaded the eBook and can confirm.
