### ISSUE TITLE
Chapter 8 - version 1 - Save does not save edits

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#16]
Clicking the save button does not save the edits.

**Comment by driscollis** [comment]
Well, it does save the edits, but it's not updating the main app. Not sure why I didn't notice that, but I am working on a fix

**Comment by cmcknight** [comment]
Thanks, I just validated that the edits are in fact saved.

**Comment by cmcknight** [comment]
Also, I know you're working on a fix, but shouldn't the ObjectListView be cleared if you select another folder? :-)

**Comment by driscollis** [comment]
I could see an argument for the current way it works, but I like this suggestion better. I just updated the code with the fixes including clearing the widget on load.

**Comment by cmcknight** [comment]
Sure, but then the app would have to keep track of a lot of other information. Nice project extension but then again I’m guilty of editing ID3 tags using Vim.  ;-)
