### ISSUE TITLE
Chapter 9 - main.py script text

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#18]
In the text of the book the start of **main.py** is:

    # main.py
    
    import wx
    
    from advanced_search import RegularSearch
    from regular_search import SearchResults
    from pubsub import pub

The code in the repository reads:

    # main.py
    
    import wx
    
    from advanced_search import AdvancedSearch
    from regular_search import RegularSearch
    from pubsub import pub

**Comment by driscollis** [comment]
Good catch. Sorry I missed that
