### ISSUE TITLE
Chapter 10 - Code in book is different than code in repo

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#19]
In the split_panel.py code in the book:

    if ',' in split_options:
        pages = split_options.split(',')

        for page in pages:
            pdf_writer.addPage(pdf.getPage(int(page)))

In the repo code:

    if ',' in split_options:
        pages = [page for page in split_options.split(',')
                         if page]

        for page in pages:
            pdf_writer.addPage(pdf.getPage(int(page)))

I'm also getting an index out of range error that I'm trying to track down.

Update: I'm trying to split a 2-page PDF to keep the first test simple. I'm either getting the above error or I'm told that the method is getting 1 value when it expects 2 if I just specify a single page to split out.

**Comment by driscollis** [comment]
You caught a fun corner case. I just uploaded a fix that I think will resolve the issue. I am also going to be pushing an update to the book here shortly

**Comment by cmcknight** [comment]
Confirming that this fixed it. 👍

**Comment by driscollis** [comment]
I should make some challenge coins for people like you. Beeware has some really neat ones
