### ISSUE TITLE
Book text doesn't match repo code

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#2]
Chapter 6:

The on_total method in the book (page 69 in ePub) reads:

    def on_total(self, event):
        solution = self.update_solution()
        if solution:
            self.running_total.SetLabel('')

but the code in the repo reads:

    def on_total(self, event):
        solution = self.update_solution()
        if solution:
            self.solution.SetValue(solution)
            self.running_total.SetLabel('')

The repo code works as expected and updates the solution text control.

More book editing. :-)

**Comment by driscollis** [comment]
Good catch. Fixed locally. Will push all the book changes tonight
