### ISSUE TITLE
Chapter 11 - search_results_olv not clearing between searches

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#21]
Back-to-back searches append the new results to the search_results_olv object.

_Steps to Recreate_
1. Select folder to search
2. Enter file name to search
3. Tap Enter
4. Search results are displayed
5. Enter a new filename to search
6. Tap Enter
7. Search results are appended to original search results

I expected the ObjectListView to be cleared between searches but this is apparently not the case.

**Comment by driscollis** [comment]
That was my intent as well. I just fixed that issue
