### ISSUE TITLE
Chapter 11 - Search does not recognize mixed case filename entries

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#22]
A mixed-case filename doesn't appear to be found but using the same name unless the case sensitive checkbox is selected. However, a lowercase file name is found.

_Steps to Recreate_
1. Choose folder
2. Enter known to be good mixed-case file name
3. Tap Enter
4. Nothing gets displayed
5. Enter known to be good file name in lowercase
6. Tap Enter
7. File is displayed

My expectation would be that the case-sensitive flag would filter out file names that don't match and not display them whereas if the case-sensitive flag is not selected the control would display anything that matched regardless of case.

**Comment by driscollis** [comment]
I just tried this out with a folder that had multiple files with the same name, but different case. I had to adjust it a bit to only look at filenames instead of the full path. It seems to work correctly now with my changes.
