### ISSUE TITLE
Chapter 11 - Text Search - main.py - assigning value to preferences and never using preferences

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#23]
In the create_menu method in main.py there is a line:

        preferences = file_menu.Append(wx.ID_ANY,
                                       'Preferences',
                                       'Open Preferences Dialog')

preferences is not used afterwards, so I'm wondering if the assignment needs to occur or if it can be omitted.

**Comment by driscollis** [comment]
It should have been used in the `Bind` statement. Frankly I am surprised the menu item worked without that. I went ahead and fixed it to be consistent though.
