### ISSUE TITLE
Chapter 11 - Text Search - on_choose_folder method missing in text

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#24]
The text does not list the following method:

    def on_choose_folder(self, event):
        with wx.Dirdialog(self, 'Choose a directory:',
                          style=wx.DD_DEFAULT_STYLE,
                          ) as dlg:
            if dlg.ShowModal() == wx.ID_OK:
                self.directory.SetValue(dlg.GetPath())

the method is in the repo code though.

**Comment by driscollis** [comment]
Good point. I will mention it in the book, although since it is the same as the method from the file search utility, I don't think it needs to be reproduced in its entirety.
