### ISSUE TITLE
Repeated Code in Chapter 6

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#3]
In Chapter 6 the following code is used to create the labels for the buttons:

        buttons = [['7', '8', '9', '/'],
                   ['4', '5', '6', '*'],
                   ['1', '2', '3', '-'],
                   ['.', '0', '',  '+']]

further on in the book the same values are assigned to a different variable:

        self.whitelist = ['0', '1', '2', '3', '4',
                           '5', '6', '7', '8', '9',
                           '-', '+', '/', '*', '.']

It appears that the whitelist variable is only being used to see if the key pressed value is in the list or not. From a DRY perspective, would it be better to use the buttons list of lists variable instead of two different variables that essentially contain the same values? It would seem that using separate variables opens the door for defects if the developer forgets to update both of them.

**Comment by driscollis** [comment]
Good point. I probably would have noticed that if I had reproduced the full code for that example in the text, but I didn't. Regardless, I just fixed the example locally.
