### ISSUE TITLE
Chapter 6, Page 70 (ePub)

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#4]
The text reads:

<p style="text-indent: 1em;">“But first, you will need to modify the create_ui() method of your panel class.”</p>

The book code doesn't match the repo code with regard to eliminating the Disable() call and replacing it with the Bind() call. A suggestion would be to make the changes in the book code **bold** so that they stand out.

**Comment by driscollis** [comment]
I don't have a way to bold the code itself that I am aware of, but I am adding a comment and clarifying the explanation of that code in my text a bit. Thanks for pointing that out.
