### ISSUE TITLE
Feature Suggestion - Packaging and Installation

### ISSUE THREAD

**Issue by cmcknight** [driscollis/applications_with_wxpython#9]
This is not a bug report but a feature request to include a chapter or appendix on packaging a wxPython app for distribution across the major operating systems (Linux, MacOS, Windows).

**Comment by driscollis** [comment]
This is already a planned chapter, probably the last chapter of the book. I know how to generate executables for Windows and Mac, although I haven't actually tried to do that for Mac as of yet. There really isn't a way to target more than one version of Linux at a time, but I do plan to mention some ideas for that.
